const languageOptions = [
    { value: "", label: "Select Language" },
    { value: 'mandarin chinese', label: 'Mandarin Chinese' },
    { value: 'spanish', label: 'Spanish' },
    { value: 'english', label: 'English' },
    { value: 'hindi', label: 'Hindi' },
    { value: 'arabic', label: 'Arabic' },
    { value: 'bengali', label: 'Bengali' },
    { value: 'portuguese', label: 'Portuguese' },
    { value: 'russian', label: 'Russian' },
    { value: 'urdu', label: 'Urdu' },
    { value: 'indonesian', label: 'Indonesian' },
    { value: 'german', label: 'German' },
    { value: 'japanese', label: 'Japanese' },
    { value: 'swahili', label: 'Swahili' },
    { value: 'marathi', label: 'Marathi' },
    { value: 'telugu', label: 'Telugu' },
    { value: 'wu chinese', label: 'Wu Chinese' },
    { value: 'turkish', label: 'Turkish' },
    { value: 'korean', label: 'Korean' },
    { value: 'french', label: 'French' },
    { value: 'vietnamese', label: 'Vietnamese' },
    { value: 'tamil', label: 'Tamil' },
    { value: 'yue chinese (cantonese)', label: 'Yue Chinese (Cantonese)' },
    { value: 'italian', label: 'Italian' },
    { value: 'thai', label: 'Thai' },
    { value: 'gujarati', label: 'Gujarati' },
    { value: 'javanese', label: 'Javanese' },
    { value: 'filipino (tagalog)', label: 'Filipino (Tagalog)' },
    { value: 'persian (farsi)', label: 'Persian (Farsi)' },
    { value: 'pashto', label: 'Pashto' },
    { value: 'polish', label: 'Polish' },
    { value: 'ukrainian', label: 'Ukrainian' },
    { value: 'malayalam', label: 'Malayalam' },
    { value: 'odia (oriya)', label: 'Odia (Oriya)' },
    { value: 'maithili', label: 'Maithili' },
    { value: 'burmese', label: 'Burmese' },
    { value: 'hausa', label: 'Hausa' },
    { value: 'uzbek', label: 'Uzbek' },
    { value: 'sundanese', label: 'Sundanese' },
    { value: 'yoruba', label: 'Yoruba' },
    { value: 'amharic', label: 'Amharic' },
    { value: 'sindhi', label: 'Sindhi' },
    { value: 'fulah', label: 'Fulah' },
    { value: 'dutch', label: 'Dutch' },
    { value: 'yiddish', label: 'Yiddish' },
    { value: 'saraiki', label: 'Saraiki' },
  ];

  export default languageOptions;