const top50Languages = {
    'mandarin chinese': 'zh',
    'spanish': 'es',
    'english': 'en',
    'hindi': 'hi',
    'arabic': 'ar',
    'bengali': 'bn',
    'portuguese': 'pt',
    'russian': 'ru',
    'urdu': 'ur',
    'indonesian': 'id',
    'german': 'de',
    'japanese': 'ja',
    'swahili': 'sw',
    'marathi': 'mr',
    'telugu': 'te',
    'wu chinese': 'wuu',
    'turkish': 'tr',
    'korean': 'ko',
    'french': 'fr',
    'vietnamese': 'vi',
    'tamil': 'ta',
    'yue chinese (cantonese)': 'yue',
    'italian': 'it',
    'thai': 'th',
    'gujarati': 'gu',
    'javanese': 'jv',
    'filipino (tagalog)': 'fil',
    'persian (farsi)': 'fa',
    'pashto': 'ps',
    'polish': 'pl',
    'ukrainian': 'uk',
    'malayalam': 'ml',
    'odia (oriya)': 'or',
    'maithili': 'mai',
    'burmese': 'my',
    'hausa': 'ha',
    'uzbek': 'uz',
    'sundanese': 'su',
    'yoruba': 'yo',
    'amharic': 'am',
    'sindhi': 'sd',
    'fulah': 'ff',
    'dutch': 'nl',
    'yiddish': 'yi',
    'saraiki': 'skr'
};
  
module.exports = top50Languages;